### ISSUE TITLE
Wireflow puntjes

### ISSUE THREAD

**Issue by Amber-vdr** [Naddybs/fix-the-flow-wireflow#1]
Je wireflow in Figma ziet er goed uit. Alleen zijn er kleine dingen wat nog missen:

- [x] Nummereren, een titel en een omschrijving met wat er gebeurt in elke state
- [x] je user story verduidelijken in de wiki
- [x] in elke state verduidelijken met eventueel kleuren, wat er gebeurd
- [x] en alleen nog documenteren in de wiki

**Comment by Naddybs** [comment]
Gedaan, bedankt!
